### ISSUE TITLE
Without -u option

### ISSUE THREAD

**Issue by Iansus** [dlion/guessTor#1]
< flag as question >

Hi,
I'm not a go expert, but it seems that if you don't use the `-u` option, the tool only creates a list of random `.<tld>` domains, without any validity check ?

Thx in advance, Iansus

``` go
} else {
    fmt.Printf("http://%s.%s\n", domain, *top)
}
```

**Comment by dlion** [comment]
Exactly, if you don't want to check if domains are online you can omit the `-u` option.
with -u option:

```
./guessTor -u
http://go4lbz3zjrimu6xh.onion -- STATUS: down
```

without -u option:

```
./guessTor
http://ou2wjaafdnredwci.onion
```
